# docker-compose.yml
version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
